name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      firstName:
        default: 'FirstName'
        required: true
        type: string
      secondName:
        default: 'SecondName'
        required: true
        type: string
jobs:
  ManualInput:
    # runs-on: ubuntu-latest
    runs-on: gharunner
    steps:
    - name: Send greeting
      run: |
         echo "Hello ${{ inputs.firstName }}"
         sleep 20
         echo "Hello ${{ inputs.secondName }}"
