name: selfhostedrunner
on:
  workflow_dispatch:
    inputs:
      firstName:
        default: 'FirstName'
        required: true
        type: string
      secondName:
        default: 'SecondName'
        required: true
        type: string
jobs:
  # This workflow contains a single job called "greet"
  ManualInput:
    # The type of runner that the job will run on
    runs-on: gha-ubuntu

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
         echo "Hello ${{ inputs.firstName }}"
         echo "Hello ${{ inputs.secondName }}"
