name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      firstName:
        default: 'FirstName'
        required: true
        type: string
      secondName:
        default: 'SecondName'
        required: true
        type: string
jobs:
  ManualInput:
    runs-on: self-hosted
    steps:
    - name: Send greeting
      run: |
         echo "Hello ${{ inputs.firstName }}"
         echo "Hello ${{ inputs.secondName }}"
